name: Test Create JSON

on:
  push:
    branches:
      - main

jobs:
  test-create-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run Create JSON Action
        uses: ./.github/actions/create-json
        with:
          fields:
            a: 1
            b:
              c: 2
              d: '3'